// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/react/react-global.d.ts
/// <reference path='../react-dom/index.d.ts' />
/// <reference path='../react/index.d.ts' />
import React = __React;
import ReactDOM = __React.__DOM;